"""
    Even Fibonacci numbers
    Problem 2
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def fibonacci():
    x, y = 0, 1
    while True:
        yield x
        x, y = y, x + y


def even_sum(sequence, max_num):
    for n in sequence:
        if n >= max_num:
            break
        if n % 2 == 0:
            yield n


f = fibonacci()
g = even_sum(f, 4000000)

print sum(g)
